# Generated by Django 2.2.5 on 2019-11-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpago',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orden_pago/'),
        ),
    ]
