# Generated by Django 2.2.5 on 2019-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pago', '0002_auto_20191109_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpago',
            name='tipo_proveedor',
            field=models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], max_length=10),
        ),
    ]
