# Generated by Django 2.2.5 on 2019-12-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pago', '0003_auto_20191110_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpago',
            name='motivo_anular',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ordenpago',
            name='estado',
            field=models.CharField(blank=True, choices=[('GRBD', 'Grabado'), ('AUTR', 'Autorizado'), ('ANLD', 'Anulado')], default='GRBD', max_length=5, null=True),
        ),
    ]
