# Generated by Django 2.2.5 on 2019-09-23 22:17

from django.db import migrations, models
import django.db.models.deletion
import financiero.validaciones


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_juridicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresar nombre de evento', max_length=200, verbose_name='Nombre de Evento')),
                ('codigo', models.CharField(max_length=200, verbose_name='Código')),
                ('nombre_instructor', models.CharField(max_length=200, verbose_name='Nombre del instructor')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('horario', models.CharField(max_length=200)),
                ('n_horas', models.IntegerField(validators=[financiero.validaciones.validate_positivo], verbose_name='No. Horas')),
                ('costo_hora_instructor', models.DecimalField(decimal_places=3, max_digits=7, validators=[financiero.validaciones.validate_positivo], verbose_name='Costo Hora Instructor')),
                ('n_dias', models.IntegerField(validators=[financiero.validaciones.validate_positivo], verbose_name='No. Dias')),
                ('n_participantes', models.IntegerField(validators=[financiero.validaciones.validate_positivo], verbose_name='No. Participantes')),
                ('ingresos', models.DecimalField(decimal_places=3, max_digits=14, validators=[financiero.validaciones.validate_positivo], verbose_name='Ingresos sin descuento')),
                ('honorario_instructor', models.DecimalField(decimal_places=3, max_digits=7, validators=[financiero.validaciones.validate_positivo], verbose_name='Honorario Instructor')),
                ('movilizacion_personal', models.DecimalField(decimal_places=3, max_digits=10, validators=[financiero.validaciones.validate_positivo], verbose_name='Movilización del personal')),
                ('lapiz', models.DecimalField(decimal_places=3, max_digits=8, validators=[financiero.validaciones.validate_positivo], verbose_name='Lápiz')),
                ('pendrives', models.DecimalField(decimal_places=3, max_digits=8, validators=[financiero.validaciones.validate_positivo], verbose_name='Pendrives')),
                ('otros_materiales', models.DecimalField(decimal_places=3, max_digits=8, validators=[financiero.validaciones.validate_positivo], verbose_name='Otros materiales')),
                ('movilizacion_personal_ciudad', models.DecimalField(decimal_places=3, max_digits=10, validators=[financiero.validaciones.validate_positivo], verbose_name='Movilización del personal (dentro de la ciudad')),
                ('estado', models.BooleanField(blank=True, default=None, null=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuestos.Aula', verbose_name='Aula')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas_juridicas.Juridica', verbose_name='Empresa')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuestos.Modalidad', verbose_name='Modalidad')),
            ],
        ),
    ]
