# Generated by Django 2.2.4 on 2019-09-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='costo_hora_instructor_currency',
        ),
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='honorario_instructor_currency',
        ),
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='ingresos_currency',
        ),
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='lapiz_currency',
        ),
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='movilizacion_personal_ciudad_currency',
        ),
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='movilizacion_personal_currency',
        ),
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='otros_materiales_currency',
        ),
        migrations.RemoveField(
            model_name='presupuestoevento',
            name='pendrives_currency',
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='costo_hora_instructor',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Costo Hora Instructor'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='honorario_instructor',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Honorario Instructor'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='ingresos',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Ingresos sin descuento'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='lapiz',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Lápiz'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='movilizacion_personal',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Movilización del personal'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='movilizacion_personal_ciudad',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Movilización del personal (dentro de la ciudad'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='otros_materiales',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Otros materiales'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='pendrives',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Pendrives'),
        ),
    ]
