# Generated by Django 2.2.4 on 2019-09-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_auto_20190921_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoevento',
            name='estado',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
