# Generated by Django 2.2.4 on 2019-09-21 22:57

from django.db import migrations, models
import financiero.presupuestos.models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_auto_20190921_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoevento',
            name='lapiz',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[financiero.presupuestos.models.validate_positivo], verbose_name='Lápiz'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='otros_materiales',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[financiero.presupuestos.models.validate_positivo], verbose_name='Otros materiales'),
        ),
        migrations.AlterField(
            model_name='presupuestoevento',
            name='pendrives',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[financiero.presupuestos.models.validate_positivo], verbose_name='Pendrives'),
        ),
    ]
