# Generated by Django 2.2.4 on 2019-09-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_auto_20190921_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoevento',
            name='estado',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
