# Generated by Django 2.2.5 on 2019-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_naturales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('Natural', 'Natural'), ('Jurídica', 'Jurídica')], max_length=15)),
                ('cod_orden_fact', models.CharField(blank=True, max_length=15)),
                ('n_tramite', models.CharField(blank=True, default='No asignado', max_length=15, null=True)),
                ('n_factura', models.CharField(blank=True, default='No asignado', max_length=15, null=True)),
                ('anexo_factura', models.FileField(blank=True, null=True, upload_to='uploads/facturas/')),
                ('fecha', models.DateField()),
                ('ruc_ci', models.CharField(max_length=13)),
                ('razon_nombres', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('concepto', models.CharField(max_length=300)),
                ('centro_costo', models.CharField(max_length=100)),
                ('n_participantes', models.PositiveIntegerField()),
                ('valor_total', models.FloatField(max_length=12)),
                ('observaciones', models.CharField(max_length=500)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.BooleanField(blank=True, default=None, null=True)),
                ('participantes', models.ManyToManyField(to='personas_naturales.Persona_Natural')),
            ],
            options={
                'ordering': ['-cod_orden_fact'],
            },
        ),
    ]
