# Generated by Django 2.2.5 on 2019-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenfacturacion',
            name='estado',
            field=models.CharField(default='ACTV', max_length=5),
        ),
    ]
