# Generated by Django 2.2.5 on 2019-11-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pago', '0001_initial'),
        ('orden_facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenfacturacion',
            name='centro_costo',
        ),
        migrations.AddField(
            model_name='ordenfacturacion',
            name='centro_costos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orden_pago.Centro_Costos'),
        ),
    ]
