# Generated by Django 2.2.5 on 2019-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfacturacion',
            name='tipo_cliente',
            field=models.CharField(choices=[('p_natural', 'Natural'), ('p_juridica', 'Jurídica')], default='p_natural', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordenfacturacion',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='personas_naturales.Persona_Natural'),
        ),
    ]
