# Generated by Django 2.2.5 on 2019-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_facturacion', '0002_auto_20190924_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenfacturacion',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTV', 'Activo'), ('SLEE', 'Solicitud Enviada'), ('ACPF', 'Autorizada por Financiero'), ('IMPE', 'Impreso Emitido'), ('RGAC', 'Registrado Académico'), ('FAES', 'Con factura ESPOLTECH'), ('ANLD', 'Anulada')], default='ACTV', max_length=5, null=True),
        ),
    ]
