# Generated by Django 2.2.4 on 2019-10-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_facturacion', '0005_auto_20191005_1657'),
        ('orden_facturacion', '0005_auto_20190928_2156'),
    ]

    operations = [
    ]
