# Generated by Django 2.2.5 on 2019-10-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_facturacion', '0006_merge_20191009_2330'),
        ('orden_facturacion', '0006_merge_20191008_1529'),
    ]

    operations = [
    ]
