# Generated by Django 2.2.4 on 2019-12-01 02:03

from django.db import migrations, models
import financiero.validaciones


class Migration(migrations.Migration):

    dependencies = [
        ('orden_facturacion', '0007_merge_20191011_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfacturacion',
            name='valor_pendiente',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, validators=[financiero.validaciones.validate_positivo]),
        ),
        migrations.AlterField(
            model_name='ordenfacturacion',
            name='valor_total',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[financiero.validaciones.validate_positivo]),
        ),
    ]
