# Generated by Django 2.2.4 on 2019-09-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecontacto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.Juridica'),
        ),
    ]
