# Generated by Django 2.2.5 on 2019-09-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_juridicas', '0003_auto_20190919_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('nombreProforma', models.CharField(max_length=100)),
                ('fechaSolicitud', models.CharField(max_length=30)),
                ('fechaEnvio', models.CharField(max_length=30)),
                ('numeroParticipantes', models.PositiveIntegerField()),
                ('horas', models.PositiveIntegerField()),
                ('cantidadCursos', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('porcentExito', models.FloatField()),
                ('porcentDesc', models.FloatField()),
                ('montoProforma', models.FloatField()),
                ('montoDesc', models.FloatField()),
                ('observacion', models.CharField(max_length=500)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRespuesta', models.CharField(blank=True, max_length=30, null=True)),
                ('montoAceptado', models.FloatField(blank=True, null=True)),
                ('montoEjecutado', models.FloatField(blank=True, null=True)),
                ('montoPorEjecutarse', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.Juridica')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.Sector')),
                ('tipoEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.TipoEmpresa')),
            ],
        ),
    ]
