# Generated by Django 2.2.5 on 2019-10-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
