# Generated by Django 2.2.5 on 2019-09-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.Sector'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tipoEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.TipoEmpresa'),
        ),
    ]
