# Generated by Django 2.2.5 on 2019-09-10 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporte_contacto', '0001_initial'),
        ('propuesta_corp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestacorporativo',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_contacto.ReporteContacto'),
        ),
    ]
