# Generated by Django 2.2.5 on 2019-09-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Sector')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=250)),
                ('maximo_facturas', models.DateField()),
                ('forma_pago', models.CharField(max_length=100)),
                ('contacto_cedula', models.CharField(max_length=13)),
                ('contacto_nombres', models.CharField(max_length=75)),
                ('contacto_apellidos', models.CharField(max_length=75)),
                ('contacto_cargo', models.CharField(max_length=150)),
                ('contacto_telefono', models.CharField(max_length=20)),
                ('contacto_celular', models.CharField(max_length=20)),
                ('contacto_correo', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas_juridicas.Ciudad')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas_juridicas.Provincia')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas_juridicas.Sector')),
                ('tipo_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas_juridicas.TipoEmpresa')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.Provincia'),
        ),
    ]
