# Generated by Django 2.2.5 on 2019-09-20 02:09

from django.db import migrations, models
import ventas.validaciones


class Migration(migrations.Migration):

    dependencies = [
        ('personas_naturales', '0003_auto_20190919_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_natural',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[ventas.validaciones.validate_cedula], verbose_name='Cédula'),
        ),
    ]
