# Generated by Django 2.2.5 on 2019-09-10 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas_juridicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona_Natural',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('apellidos', models.CharField(max_length=75)),
                ('nombres', models.CharField(max_length=75)),
                ('fecha_nacimiento', models.CharField(help_text='DD-MM-AAAA', max_length=12, verbose_name='Fecha de Nacimiento')),
                ('tel_domicilio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Domicilio')),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dir_domicilio', models.CharField(max_length=75, verbose_name='Dirección Domicilio')),
                ('nivel_estudio', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Tercer Nivel', 'Tercer Nivel'), ('Postgrado', 'Postgrado')], default='Primaria', max_length=50, verbose_name='Nivel de Estudio')),
                ('ti_tercernivel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título Tercer Nivel')),
                ('un_tercernivel', models.CharField(blank=True, max_length=75, null=True, verbose_name='Universidad Tercer Nivel')),
                ('ti_cuartonivel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo Cuarto Nivel')),
                ('un_cuartonivel', models.CharField(blank=True, max_length=75, null=True, verbose_name='Universidad Cuarto Nivel')),
                ('profesion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesión')),
                ('forma_trabajo', models.CharField(blank=True, choices=[('Dependiente', 'Dependiente'), ('Independiente', 'Profesional Independiente')], max_length=100, null=True, verbose_name='Forma de Trabajo')),
                ('empresa', models.CharField(blank=True, max_length=75, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Área/Departamento')),
                ('dir_trabajo', models.CharField(blank=True, max_length=75, null=True, verbose_name='Dirección Trabajo')),
                ('tel_trabajo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono Trabajo')),
                ('red_social', models.CharField(max_length=50, verbose_name='Red Social por donde se enteró de este evento')),
                ('ci_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad_domicilio_set', to='personas_juridicas.Ciudad', verbose_name='Ciudad Domicilio')),
                ('ci_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad_trabajo_set', to='personas_juridicas.Ciudad', verbose_name='Ciudad Trabajo')),
            ],
        ),
    ]
