# Generated by Django 2.2.4 on 2019-09-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas_naturales', '0002_auto_20190907_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_natural',
            name='ci_domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad_domicilio_set', to='personas_juridicas.Ciudad', verbose_name='Ciudad Domicilio'),
        ),
        migrations.AlterField(
            model_name='persona_natural',
            name='ci_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudad_trabajo_set', to='personas_juridicas.Ciudad', verbose_name='Ciudad Trabajo'),
        ),
    ]
