# Generated by Django 2.2.4 on 2019-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('nombreProforma', models.CharField(max_length=100)),
                ('tipoEmpresa', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=20)),
                ('fechaSolicitud', models.DateField()),
                ('fechaEnvio', models.DateField()),
                ('numeroParticipantes', models.PositiveIntegerField()),
                ('horas', models.PositiveIntegerField()),
                ('cantidadCursos', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('porcentExito', models.FloatField()),
                ('porcentDesc', models.FloatField()),
                ('montoProforma', models.FloatField()),
                ('montoDesc', models.FloatField()),
                ('observacion', models.CharField(max_length=500)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaRespuesta', models.DateField(blank=True, null=True)),
                ('montoAceptado', models.FloatField(blank=True, null=True)),
                ('montoEjecutado', models.FloatField(blank=True, null=True)),
                ('montoPorEjecutarse', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
