# Generated by Django 2.2.4 on 2019-09-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='fechaEnvio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='fechaRespuesta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='fechaSolicitud',
            field=models.CharField(max_length=30),
        ),
    ]
