# Generated by Django 2.2.4 on 2019-09-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0003_auto_20190910_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas_juridicas.Juridica'),
        ),
    ]
