# Generated by Django 2.2.5 on 2019-09-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propuesta_corp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestacorporativo',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas_juridicas.Sector'),
        ),
    ]
