# Generated by Django 2.2.5 on 2019-09-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=12)),
                ('numeroTramite', models.PositiveIntegerField()),
                ('numeroFactura', models.PositiveIntegerField()),
                ('identificacion', models.CharField(max_length=10)),
                ('razonSocial', models.CharField(max_length=50)),
                ('centroCosto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
                ('anexo', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
