# Generated by Django 2.2.4 on 2019-09-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeningreso',
            name='emisoraTarjeta',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american', 'American Express'), ('diners', 'Diners'), ('discover', 'Discover')], max_length=20),
        ),
    ]
