# Generated by Django 2.2.4 on 2019-09-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_ingreso', '0002_auto_20190923_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeningreso',
            name='emisoraTarjeta',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american', 'American Express'), ('diners', 'Diners'), ('discover', 'Discover')], help_text='Obligatorio si Tarjeta de Crédito es seleccionado.', max_length=20),
        ),
    ]
