# Generated by Django 2.2.5 on 2019-09-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_ingreso', '0003_auto_20190923_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeningreso',
            name='emisoraTarjeta',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american', 'American Express'), ('diners', 'Diners'), ('discover', 'Discover')], help_text='Obligatorio con Tarjeta Crédito.', max_length=20),
        ),
    ]
